defmodule Riffle.Predicate.DefaultPipelineConfig do
  @moduledoc """
  Default implementation of PipelineConfig for DSL-based pipeline modules.

  This module provides a standard implementation of the PipelineConfig behaviour
  that can be easily used by pipeline definition modules through `use` macro.

  ## Example

      defmodule MyPipelines do
        use Riffle.Predicate.Dsl.Macro
        use Riffle.Predicate.DefaultPipelineConfig
        
        # Define pipelines, loops, and predicates...
        defpipeline :main, "Main pipeline" do
          loop(:my_loop)
        end
      end
  """

  defmacro __using__(_opts) do
    quote do
      @behaviour Riffle.Predicate.PipelineConfig

      # Standard implementation of get_pipeline for atom names
      @impl true
      def get_pipeline(name) when is_atom(name) do
        # Pipeline definitions are just functions with arity 0
        # so we can simply call the function with the given name
        try do
          apply(__MODULE__, name, [])
        rescue
          # Return nil when the pipeline function doesn't exist
          UndefinedFunctionError -> nil
        end
      end

      # Standard implementation of get_pipeline for string names
      @impl true
      def get_pipeline(name) when is_binary(name) do
        try do
          get_pipeline(String.to_existing_atom(name))
        rescue
          # Return nil when the name can't be converted to an existing atom
          ArgumentError -> nil
        end
      end

      # Standard implementation of get_loop
      @impl true
      def get_loop(name) when is_atom(name) do
        # The loops() function is generated by the DSL.Macro
        loops = __MODULE__.loops()
        Map.get(loops, name)
      end

      # Standard implementation of get_predicate
      @impl true
      def get_predicate(name) when is_atom(name) do
        # The predicates() function is generated by the DSL.Macro
        predicates = __MODULE__.predicates()
        Map.get(predicates, name)
      end

      # Standard implementation of list_pipelines
      @impl true
      def list_pipelines do
        # Find all pipeline functions (with arity 0)
        __MODULE__.__info__(:functions)
        |> Enum.filter(fn {_, arity} -> arity == 0 end)
        |> Enum.map(fn {name, _} -> name end)
        |> Enum.reject(&(&1 in [:predicates, :loops, :pipelines]))
      end

      # Allow modules to override these functions if needed
      defoverridable get_pipeline: 1, get_loop: 1, get_predicate: 1, list_pipelines: 0
    end
  end
end
