defmodule Riffle.Predicate.DefaultPipelineConfig do
  @moduledoc """
  Default implementation of PipelineConfig for DSL-based pipeline modules.

  This module provides a standard implementation of the PipelineConfig behaviour
  that can be easily used by pipeline definition modules through `use` macro.

  ## Example

      defmodule MyPipelines do
        use Riffle.Predicate.Dsl.Macro
        use Riffle.Predicate.DefaultPipelineConfig
        
        # Define pipelines, loops, and predicates...
        defpipeline :main, "Main pipeline" do
          loop(:my_loop)
        end
      end
  """

  defmacro __using__(_opts) do
    quote do
      @behaviour Riffle.Predicate.PipelineConfig

      # Standard implementation of get_pipeline for atom names
      @impl true
      def get_pipeline(name) when is_atom(name) do
        # Membership comes from the canonical pipelines() map generated by
        # the DSL macro -- never from function reflection, which would also
        # answer for the zero-arity loop and predicate accessors.
        case Map.fetch(__MODULE__.pipelines(), name) do
          {:ok, _definition} -> apply(__MODULE__, name, [])
          :error -> nil
        end
      end

      # Standard implementation of get_pipeline for string names
      @impl true
      def get_pipeline(name) when is_binary(name) do
        case Riffle.Predicate.DefaultPipelineConfig.existing_atom(name) do
          {:ok, atom} -> get_pipeline(atom)
          :error -> nil
        end
      end

      # Standard implementation of get_loop
      @impl true
      def get_loop(name) when is_atom(name) do
        # The loops() function is generated by the DSL.Macro
        loops = __MODULE__.loops()
        Map.get(loops, name)
      end

      # Standard implementation of get_predicate
      @impl true
      def get_predicate(name) when is_atom(name) do
        # The predicates() function is generated by the DSL.Macro
        predicates = __MODULE__.predicates()
        Map.get(predicates, name)
      end

      # Standard implementation of list_pipelines: the canonical map's keys
      # ARE the pipelines (reflection was a second, leaky registry).
      @impl true
      def list_pipelines do
        Map.keys(__MODULE__.pipelines())
      end

      # Allow modules to override these functions if needed
      defoverridable get_pipeline: 1, get_loop: 1, get_predicate: 1, list_pipelines: 0
    end
  end

  @doc false
  # Tagged conversion so callers pattern-match instead of nil-checking; the
  # rescue is scoped to exactly the conversion (unknown name), nothing else.
  @spec existing_atom(String.t()) :: {:ok, atom()} | :error
  def existing_atom(string) when is_binary(string) do
    {:ok, String.to_existing_atom(string)}
  rescue
    ArgumentError -> :error
  end
end
